export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';

export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';

export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';

export const SINGLE_PROJECT_SUCCESS = 'SINGLE_PROJECT_SUCCESS';

export const DELETE_PROJECT_SUCCESS = 'SINGLE_PROJECT_SUCCESS';
